# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21295fa82ec2283e76a486ba39fead76afc0a7b7eee28f915334090b9c07bb9920d138b71b17b388588c036c75490beaa642385912e9ebaefb1a7c4285a30a50

test:
  secret_key_base: 955cad81beb1b87f593ce53ce8d9786ae6227bce47ba79ca580995387df204c2da69584b9c4f2fd32fbf48c6a4fa299c88f6f2613f3a1e58ae3ab66e59177119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
